/**
 * Relation map — prepositions/conjunctions → REL tokens
 */
export const RELATION_MAP: Record<string, string> = {
  to: "REL:to",
  toward: "REL:to",
  towards: "REL:to",
  from: "REL:from",
  with: "REL:with",
  without: "REL:without",
  because: "REL:causes",
  so: "REL:causes",
  since: "REL:causes",
  therefore: "REL:causes",
  thus: "REL:causes",
  before: "REL:before",
  after: "REL:after",
  during: "REL:during",
  in: "REL:in",
  at: "REL:at",
  by: "REL:by",
  for: "REL:for",
  of: "REL:of",
  about: "REL:about",
  between: "REL:between",
  among: "REL:among",
  amongst: "REL:among",
  through: "REL:through",
  across: "REL:across",
  along: "REL:along",
  around: "REL:around",
  within: "REL:within",
  upon: "REL:upon",
  above: "REL:above",
  below: "REL:below",
  under: "REL:under",
  over: "REL:over",
  near: "REL:near",
  beside: "REL:beside",
  behind: "REL:behind",
  beyond: "REL:beyond",
  against: "REL:against",
  despite: "REL:despite",
  although: "REL:contrast",
  though: "REL:contrast",
  however: "REL:contrast",
  whereas: "REL:contrast",
  while: "REL:contrast",
  and: "REL:and",
  or: "REL:or",
  but: "REL:but",
  nor: "REL:nor",
  if: "REL:condition",
  unless: "REL:condition",
  whether: "REL:condition",
  per: "REL:per",
  via: "REL:via",
  versus: "REL:versus",
  like: "REL:like",
  unlike: "REL:unlike",
  except: "REL:except",
  besides: "REL:besides",
  instead: "REL:instead",
  rather: "REL:instead",
  including: "REL:including",
  such: "REL:like",
  // ── Directional / Spatial particles ──
  on: "REL:on",
  onto: "REL:onto",
  into: "REL:into",
  up: "REL:up",
  down: "REL:down",
  out: "REL:out",
  off: "REL:off",
  // ── Comparison / Degree ──
  as: "REL:as",
  than: "REL:compare",
  // ── Relative / Interrogative pronouns (relational connectors) ──
  that: "REL:that",
  who: "REL:who",
  whom: "REL:whom",
  which: "REL:which",
  what: "REL:what",
  where: "REL:where",
  when: "REL:when",
  how: "REL:how",
  why: "REL:why",
  // ── Demonstrative deictics ──
  this: "REL:this",
  these: "REL:these",
  those: "REL:those",
  // ── Quantifiers (structurally meaningful) ──
  all: "REL:all",
  each: "REL:each",
  every: "REL:every",
  some: "REL:some",
  any: "REL:any",
  both: "REL:both",
  many: "REL:many",
  much: "REL:much",
  more: "REL:more",
  most: "REL:most",
  few: "REL:few",
  less: "REL:less",
  other: "REL:other",
  another: "REL:another",
  // ── Temporal connectors ──
  then: "REL:then",
  still: "REL:still",
  yet: "REL:yet",
  already: "REL:already",
  once: "REL:once",
  also: "REL:also",
  only: "REL:only",
  even: "REL:even",
  just: "REL:just",
  // ── Possessive pronouns (relational: ownership) ──
  their: "REL:possess",
  your: "REL:possess",
  its: "REL:possess",
  our: "REL:possess",
  his: "REL:possess",
  her: "REL:possess",
  my: "REL:possess",
  // ── Pronominal references ──
  them: "REL:them",
  us: "REL:us",
  there: "REL:there",
  here: "REL:here",
  // ── Verbal auxiliaries (structural) ──
  being: "REL:being",
  been: "REL:been",
  having: "REL:having",
  // ── Discourse connectors ──
  according: "REL:according",
  well: "REL:well",
  indeed: "REL:indeed",
  especially: "REL:emphasis",
  particularly: "REL:emphasis",
  mainly: "REL:emphasis",
  mostly: "REL:emphasis",
  generally: "REL:general",
  usually: "REL:usual",
  often: "REL:frequent",
  sometimes: "REL:sometimes",
  always: "REL:always",
  never: "REL:never",
  together: "REL:together",
  apart: "REL:apart",
  away: "REL:away",
  back: "REL:back",
  enough: "REL:enough",
  least: "REL:least",
  // ── Prefix fragments ──
  non: "REL:negate",
  // ── Additional pronouns/connectors ──
  him: "REL:him",
  themselves: "REL:themselves",
  itself: "REL:itself",
  himself: "REL:himself",
  herself: "REL:herself",
  ourselves: "REL:ourselves",
  yourself: "REL:yourself",
  throughout: "REL:through",
  either: "REL:either",
  neither: "REL:neither",
  several: "REL:several",
  others: "REL:other",
  due: "REL:causes",
  now: "REL:now",
  far: "REL:far",
  perhaps: "REL:maybe",
  maybe: "REL:maybe",
  likely: "REL:likely",
  almost: "REL:almost",
  nearly: "REL:almost",
  quite: "REL:quite",
  rather: "REL:instead",
  merely: "REL:only",
  simply: "REL:only",
  otherwise: "REL:contrast",
  furthermore: "REL:and",
  moreover: "REL:and",
  meanwhile: "REL:during",
  therefore: "REL:causes",
  consequently: "REL:causes",
  accordingly: "REL:causes",
  hence: "REL:causes",
  subsequently: "REL:after",
  previously: "REL:before",
  formerly: "REL:before",
  increasingly: "REL:more",
  relatively: "REL:compare",
  approximately: "REL:about",
  roughly: "REL:about",
  exactly: "REL:exactly",
  precisely: "REL:exactly",
  entirely: "REL:all",
  completely: "REL:all",
  highly: "REL:emphasis",
  largely: "REL:emphasis",
  primarily: "REL:emphasis",
  notably: "REL:emphasis",
  significantly: "REL:emphasis",
  essentially: "REL:emphasis",
  typically: "REL:usual",
  commonly: "REL:usual",
  frequently: "REL:frequent",
  rarely: "REL:few",
  seldom: "REL:few",
  eventually: "REL:then",
  finally: "REL:then",
  currently: "REL:now",
  recently: "REL:now",
  immediately: "REL:now",
  directly: "REL:to",
  effectively: "REL:emphasis",
  successfully: "REL:emphasis",
  specifically: "REL:emphasis",
  certainly: "REL:emphasis",
  clearly: "REL:emphasis",
  apparently: "REL:like",
  obviously: "REL:emphasis",
  presumably: "REL:maybe",
  supposedly: "REL:maybe",
  allegedly: "REL:maybe",
  potentially: "REL:maybe",
  virtually: "REL:almost",
  extremely: "REL:emphasis",
  severely: "REL:emphasis",
  deeply: "REL:emphasis",
  widely: "REL:emphasis",
  closely: "REL:near",
  separately: "REL:apart",
  simultaneously: "REL:during",
  respectively: "REL:each",
  similarly: "REL:like",
  differently: "REL:contrast",
  regardless: "REL:despite",
  // ── Additional missed connectors/particles ──
  until: "REL:until",
  further: "REL:more",
  furthermore: "REL:and",
  something: "REL:some",
  anything: "REL:any",
  nothing: "REL:none",
  everything: "REL:all",
  someone: "REL:some",
  anyone: "REL:any",
  everyone: "REL:all",
  nobody: "REL:none",
  somewhere: "REL:some",
  anywhere: "REL:any",
  everywhere: "REL:all",
  nowhere: "REL:none",
  cannot: "REL:negate",
  sure: "REL:emphasis",
  done: "REL:complete",
  able: "REL:able",
  itself: "REL:itself",
  very: "REL:emphasis",
  too: "REL:also",
  let: "REL:permit",
  actually: "REL:emphasis",
  lot: "REL:quantity",
  brought: "REL:cause",
  c: "REL:ref",
  b: "REL:ref",
};

/**
 * Function words — always emit as LIT (no semantic decomposition)
 */
export const FUNCTION_WORDS = new Set([
  "the",
  "a",
  "an",
  "i",
  "me",
  "my",
  "mine",
  "myself",
  "you",
  "your",
  "yours",
  "yourself",
  "he",
  "him",
  "his",
  "himself",
  "she",
  "her",
  "hers",
  "herself",
  "it",
  "its",
  "itself",
  "we",
  "us",
  "our",
  "ours",
  "ourselves",
  "they",
  "them",
  "their",
  "theirs",
  "themselves",
  "this",
  "that",
  "these",
  "those",
  "is",
  "am",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "do",
  "does",
  "did",
  "has",
  "have",
  "had",
  "will",
  "would",
  "shall",
  "should",
  "can",
  "could",
  "may",
  "might",
  "must",
  "not",
  "n't",
  "no",
  "very",
  "too",
  "also",
  "just",
  "only",
  "here",
  "there",
  "where",
  "when",
  "how",
  "what",
  "which",
  "who",
  "whom",
  "then",
  "than",
  "as",
  "while",
  "yet",
  "still",
  "up",
  "down",
  "out",
  "off",
  "on",
  "into",
  "onto",
  "each",
  "every",
  "all",
  "both",
  "some",
  "any",
  "many",
  "much",
  "more",
  "most",
  "few",
  "less",
  "other",
  "another",
  "such",
]);
